#!/usr/bin/bash

RS=$'\x1E' # Record Separator
FS=$'\x1F' # Field  Separator

function process_records() {
  local CALLBACK="$1"
  local RS="$2"
  local FS="$3"

  local -a LINE

  while IFS="$FS" read -r -d "$RS" -a LINE ; do
      $CALLBACK "${LINE[@]}"
  done
}
