#!/usr/bin/bash

source ./import

import "watchfiles"
import "json/read_jsonline"

#import "json/write_jsonline"
#write_jsonline a=2 b="3 2"

watchfiles ../foo \
	| while read_jsonline events ; do
		echo "$EVENTS"
	done
