#!/usr/bin/bash

# We use an h4ck to ensure proper parsing
import "read/read_record"
import "json/write_jsonline"

# Usage: watchfiles FILES[...]
function watchfiles() {

	declare FILES="$@"
	declare ISO_FORMAT='%FT%H:%M:%S%Z'                # 2000-01-01T01:01:01+01:00

	# we use an h4ck to ensure proper parsing.
 	declare OUT_FORMAT="%T${FS}%w${FS}%e${FS}%f${RS}" # TIME WATCHED EVENTS FILE

 	# --exclude $PATTERN
 	# --include $PATTERN

	declare COMPAT=""
	if [[ ! -t 1 ]] ; then
		COMPACT="-c"
	fi

 	inotifywait -q --monitor -r "$FILES" --format  "$OUT_FORMAT" --timefmt "$ISO_FORMAT" --no-newline \
    		| while read_record RECORD ; do
			write_jsonline	watched="${RECORD[0]}" \
					   time="${RECORD[1]}" \
					 events="${RECORD[2]}" \
					   file="${RECORD[3]}"
		done
}
