#!/usr/bin/bash

function json_extract() {

	declare LINE="$1"

	declare -g -A "$2"
	declare -n RESULT="$2"

	declare VALUE

	#declare NAMES="$@"
	declare NAMES=$(jq -r 'keys[]' <<< "$LINE")

	# not ideal, but the safest for now
	for NAME in $NAMES; do
		# -r = raw output
		VALUE=$(jq -r ".$NAME" <<< "$LINE")
		RESULT["$NAME"]="$VALUE"
		#declare -g "${NAME^^}"="$VALUE"
	done
}
