#!/usr/bin/bash

function readline() {
	declare VARNAME="$1"
	shift

	# si stdin est le terminal, permettre l'édition de la ligne.
	declare EDITOR=""
	if [[ -t 0 ]] ; then
		EDITOR="-e"
	fi

	# IFS="" -r -d $'\n' : lire la ligne sans rien interpréter.
	IFS="" read -r $EDITOR -d $'\n' "$VARNAME" "$@"
}
