#!/usr/bin/bash

function read_args() {
	declare EDITOR=""
	declare VARNAME="$1"
	shift

	# si stdin est le terminal, permettre l'édition de la ligne.
	if [[ -t 0 ]] ; then
		EDITOR="-e"
	fi

	read $EDITOR -a "$VARNAME" "$@"
}
